### ISSUE TITLE
Fedora-Modular-27-20171004.n.0 compose is not installable 

### ISSUE THREAD

**Issue by paulwhalen** [modularity-modules/installer#1]
Testing the Fedora-Modular-27-20171004.n.0 compose nothing is selectable in 'Software selections' screen in anaconda tui as shown below:

================================================================================
================================================================================
Installation

 1) [ ] Language settings                 2) [!] Time settings
        (English (United States))                (Timezone is not set.)
 3) [x] Installation source               4) [!] Software selection
        (https://kojipkgs.fedoraproject          (Nothing selected)
        .org/compose/Fedora-Modular-27-   6) [x] Network configuration
        20171004.n.0/compose/Server/aar          (Wired (enp1s0) connected)
        ch64/os/)                         8) [!] User creation
 5) [!] Installation Destination                 (No user will be created)
        (No disks selected)
 7) [!] Root password
        (Password is not set.)

Please make a selection from the above ['b' to begin installation, 'h' to help,
'q' to quit, 'r' to refresh]: 4
================================================================================
================================================================================
Software selection

Base environment

Please make a selection from the above ['c' to continue, 'h' to help, 'q' to
quit, 'r' to refresh]: 

Another note, during the boot:
"Welcome to Fedora Modular 28 (Twenty Eight)!"

**Comment by paulwhalen** [comment]
appears to be missing the comps file, if thats used in the modular world.

**Comment by ausil** [comment]
anaconda uses environments in cmps to determine what to present as installable in the traditional world, has it been taught how to display and use modules? and then to install modules.

**Comment by KarstenHopp** [comment]
latest composes are installable
