### ISSUE TITLE
module remove fails 

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/installer#2]
@KarstenHopp: 
on Modular-Bikeshed-20171023

$ dnf module remove installer                                      
Error: 
 Problem: The operation would result in removing the following protected packages: systemd-udev

**Comment by KarstenHopp** [comment]
I won't worry about this one. The installer module isn't supposed to be installed in a running system at all. It is just used for the installation of a system, in the iso. Likewise there certainly are lots of conflicts when you try to install everything from the installer module together with other modules.
