### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/installer#3]
@KarstenHopp

Problem 1: 
- conflicting requests  - nothing provides python3-simpleline >= 0.6-1 needed by anaconda-tui-27.20.4-2.boltron.1.module_e8e2a93e.x86_64

Problem 2:
- package anaconda-gui-27.20.4-2.boltron.1.module_e8e2a93e.x86_64 requires anaconda-core = 27.20.4-2.boltron.1.module_e8e2a93e, but none of the providers can be installed
- package anaconda-core-27.20.4-2.boltron.1.module_e8e2a93e.x86_64 requires anaconda-tui = 27.20.4-2.boltron.1.module_e8e2a93e, but none of the providers can be installed 
- conflicting requests  - nothing provides python3-simpleline >= 0.6-1 needed by anaconda-tui-27.20.4-2.boltron.1.module_e8e2a93e.x86_64

**Comment by nphilipp** [comment]
[Here's how to fix issues like this.](https://docs.pagure.org/modularity/development/building-modules/installation-dependency-issues.html)

**Comment by alexxa** [comment]
Fixed. Closing.
